services:
  mysql:
    image: mysql:8.4
    ports:
      - "3306:3306"
    environment:
        MYSQL_DATABASE: test
        MYSQL_ROOT_PASSWORD: 12345678
        MYSQL_USER: mule
        MYSQL_PASSWORD: 12345678
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql:


