services:
  maven-app:
    image: maven:3.9.9-amazoncorretto-17-al2023
    volumes:
      - ./dock:/usr/src/app
      - maven-repo:/root/.m2
    working_dir: /usr/src/app
    command: mvn clean install
    ports:
      - "8080:8080"

volumes:
  maven-repo:
#"$(pwd)":/usr/src/mymaven -w /usr/src/mymaven maven:3.3-jdk-8 mvn clean install